server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/library
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  servlet:
    multipart:
        max-file-size: 100MB
        max-request-size: 100MB

  messages:
    basename: messages,errors

logging:
  level:
    root: info
    org.hibernate-SQL: debug
    org.hibernate.type: trace

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

file:
  dir: C:/Users/JooYoungKim/Desktop/spring/files/